export const tutors = [
  {
    id: 1,
    name: 'Dr. Sarah Khan',
    subject: 'Mathematics & Calculus',
    university: 'Harvard University',
    rating: 4.9,
    reviews: 42,
    hourlyRate: 35,
    bio: 'PhD in Mathematics with 5+ years of tutoring experience. Specialized in Calculus, Linear Algebra, and Differential Equations.',
    availability: 'Mon-Fri, 9AM-6PM',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80',
    verified: true,
    subjects: ['Calculus', 'Linear Algebra', 'Statistics', 'Physics'],
  },
  {
    id: 2,
    name: 'Ali Hassan',
    subject: 'Computer Science',
    university: 'MIT',
    rating: 4.8,
    reviews: 28,
    hourlyRate: 30,
    bio: 'Senior CS student specializing in Data Structures, Algorithms, and Web Development. Passionate about helping students grasp complex concepts.',
    availability: 'Tue-Thu, 2PM-8PM',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80',
    verified: true,
    subjects: ['Data Structures', 'Algorithms', 'Python', 'Web Dev'],
  },
  {
    id: 3,
    name: 'Emma Wilson',
    subject: 'Physics & Chemistry',
    university: 'Stanford University',
    rating: 4.7,
    reviews: 35,
    hourlyRate: 32,
    bio: 'Dual major in Physics and Chemistry. Focus on conceptual understanding and problem-solving techniques for STEM courses.',
    availability: 'Mon-Wed-Fri, 10AM-4PM',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80',
    verified: true,
    subjects: ['Physics', 'Chemistry', 'Thermodynamics', 'Organic Chem'],
  },
  {
    id: 4,
    name: 'Michael Chen',
    subject: 'Economics & Finance',
    university: 'University of Chicago',
    rating: 4.6,
    reviews: 19,
    hourlyRate: 28,
    bio: 'Economics graduate student with professional tutoring experience. Expert in Micro/Macro economics, Finance, and Econometrics.',
    availability: 'Weekends, 12PM-6PM',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80',
    verified: false,
    subjects: ['Microeconomics', 'Macroeconomics', 'Finance', 'Statistics'],
  },
  {
    id: 5,
    name: 'Jessica Lee',
    subject: 'Biology & Medicine',
    university: 'Johns Hopkins University',
    rating: 4.9,
    reviews: 51,
    hourlyRate: 40,
    bio: 'Medical student with strong background in Biology, Anatomy, and Physiology. Helps pre-med students ace their courses.',
    availability: 'Thu-Sun, 1PM-9PM',
    avatar: 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=150&q=80',
    verified: true,
    subjects: ['Biology', 'Anatomy', 'Physiology', 'Biochemistry'],
  },
  {
    id: 6,
    name: 'David Park',
    subject: 'Engineering',
    university: 'Georgia Tech',
    rating: 4.5,
    reviews: 23,
    hourlyRate: 25,
    bio: 'Mechanical Engineering graduate. Tutoring in Engineering fundamentals, CAD, Thermodynamics, and Mechanics.',
    availability: 'Mon-Fri, 5PM-10PM',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80',
    verified: true,
    subjects: ['Mechanical Engineering', 'CAD', 'Thermodynamics', 'Statics'],
  },
];
